# Jupyter

#cell type, tab, shift-tab, multi-cursor, line begin-end

# Lists

In [65]:
#create, append ++
mylist = [1,2,3,4]
mylist.append(5)
mylist.append([6])
mylist.append(7)
mylist+=[8]
mylist = mylist+[9]
mylist

[1, 2, 3, 4, 5, [6], 7, 8, 9]

In [66]:
#slice
mylist = [0,1, 2, 3, 4, 5, 6, 7, 8, 9]
print(mylist[5])
print(mylist[:5])
print(mylist[5:])
print(mylist[4:8])
print(mylist[-1])
print(mylist[-3:])
print(mylist[:-3])
print(mylist[-5:-3])

5
[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[4, 5, 6, 7]
9
[7, 8, 9]
[0, 1, 2, 3, 4, 5, 6]
[5, 6]


In [67]:
#reverse
mylist = [0,1, 2, 3, 4, 5, 6, 7, 8, 9]
mylist[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [68]:
#zip
a = [1,2,3]
b = [4,5]
list(zip(a,b))

[(1, 4), (2, 5)]

In [69]:
#flatten
mylist = [[0],[1,2],[3,[4,5]],[6,7]]
[a for b in mylist for a in b]

[0, 1, 2, 3, [4, 5], 6, 7]

In [70]:
#list comprehension
mylist = [1,2,3]
[x**2 for x in mylist]

[1, 4, 9]

In [71]:
#list comprehension con condizione
mylist = [1,2,3,4,5,6,7,8,9]
[x**2 for x in mylist if x%2==0]

[4, 16, 36, 64]

In [72]:
#list comprehension if-then-else
mylist = [0,1,2,3,4,5,6,7,8,9]
[x**2 if x%2==0 else 'dispari' for x in mylist if x<7]

[0, 'dispari', 4, 'dispari', 16, 'dispari', 36]

In [73]:
#sorting() e .sort()
mylist = [4,0,2,3,10,8,7]
sorted_list = sorted(mylist)
print(mylist)
print(sorted_list)

[4, 0, 2, 3, 10, 8, 7]
[0, 2, 3, 4, 7, 8, 10]


In [74]:
mylist = [4,0,2,3,10,8,7]
sorted_list = mylist.sort()
print(mylist)
print(sorted_list)

[0, 2, 3, 4, 7, 8, 10]
None


In [75]:
#range
list(range(5,20,2))

[5, 7, 9, 11, 13, 15, 17, 19]

In [76]:
#basic loop
for i in range(3,7):
    print('a'*i)

aaa
aaaa
aaaaa
aaaaaa


In [77]:
#enumeration
for i,e in enumerate('abcde'):
    print(i,e)

0 a
1 b
2 c
3 d
4 e


In [78]:
my_string = 'abcde'
for index in range(len(my_string)):
    print(index,my_string[index])

0 a
1 b
2 c
3 d
4 e


# Dictionaries

In [79]:
#create empty, create from vals, create from lists
mydict = {}
mydict = {1:'a',2:'b'}
print(mydict)
mydict[1]

{1: 'a', 2: 'b'}


'a'

In [80]:
#insert, access
mydict = {1:'a',2:'b'}
mydict[3] = 'c'
mydict[3] = 'd'
mydict

{1: 'a', 2: 'b', 3: 'd'}

In [81]:
#default value
mydict = {1:'a',2:'b'}
mydict.get(3,'not_found')

'not_found'

In [82]:
#esempio di count dictionary
my_string = 'kjdhfkdchdkchlksejhlksh'
count_dict = {}
for letter in my_string:
    count_dict[letter]=count_dict.get(letter,0)+1
count_dict

{'k': 5, 'j': 2, 'd': 3, 'h': 5, 'f': 1, 'c': 2, 'l': 2, 's': 2, 'e': 1}

In [83]:
#keys, items, values
print(count_dict.keys())
print(count_dict.values())
print(count_dict.items())

dict_keys(['k', 'j', 'd', 'h', 'f', 'c', 'l', 's', 'e'])
dict_values([5, 2, 3, 5, 1, 2, 2, 2, 1])
dict_items([('k', 5), ('j', 2), ('d', 3), ('h', 5), ('f', 1), ('c', 2), ('l', 2), ('s', 2), ('e', 1)])


In [84]:
# merge dictionaries, overwrite
d1 = {'a':1,'b':2}
d2 = {'b':3,'c':4}
d3 = {**d2, **d1}
d3

{'b': 2, 'c': 4, 'a': 1}

In [85]:
#delete element
del d3['a']
d3

{'b': 2, 'c': 4}

In [64]:
#pop
elem = d3.pop('b')
print(elem)
print(d3)

2
{'c': 4}


# Functions

In [ ]:
#definition, calling
def my_fun_1(myarg):
    print('argomento',myarg)
    return None

my_fun_1(1234)

In [ ]:
#default arguments
def my_fun_2(myarg=9):
    print('argomento',myarg)
    return None

my_fun_2()

# Numpy

In [86]:
import numpy as np

In [87]:
#creation of numpy array
my_list = [1,2,3,4]
my_array = np.array(my_list)
print(my_list,type(my_list))
print(my_array,type(my_array))

[1, 2, 3, 4] <class 'list'>
[1 2 3 4] <class 'numpy.ndarray'>


In [89]:
#semantica del +
a = [1,2,3]
b = [4,5,6]
print('list',a,b,a+b)
npa = np.array(a)
npb = np.array(b)
print('np.array',npa,npb,npa+npb)

list [1, 2, 3] [4, 5, 6] [1, 2, 3, 4, 5, 6]
np.array [1 2 3] [4 5 6] [5 7 9]


In [91]:
#element-wise ops e broadcasting
my_array = np.array([1,2,3])
my_array*10

array([10, 20, 30])

In [95]:
#masking
my_array = np.array([1,2,3,4,5,6,7,8])
print(my_array)
my_array[my_array%2==0]

[1 2 3 4 5 6 7 8]


array([2, 4, 6, 8])

In [103]:
#zeros, shape
my_array = np.array(range(12))
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [104]:
my_array.shape

(12,)

In [105]:
np.reshape(my_array,(3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
np.reshape(my_array,(3,-1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])